### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [evKoval/duckHuntJS#1]
Hi, this is such a great project! Is this released under any specific license or are you ok with me forking the project to add a new feature? My intention is to fork it with the added features and host it on Glitch.com and leave your name/README as is, plus a link back to this repo and your social media if you have one.

Also are you on Twitter or Dev.to, how would you like me to attribute it if it's ok?
Thanks!

**Edit:** Here are my changes: https://github.com/checkboxoz/duckfacehunt. It lets you play with face gestures
![](https://media.giphy.com/media/Ssla2T8SLQGQIisFG9/source.gif)

**Comment by ghost** [comment]
Nevermind I'm going to try and make one from scratch! You're project is super inspiring, thanks for making it!

**Comment by evKoval** [comment]
Hi! Great job! Yes You may fork it. Tell me if you need some help from me
